version: 2
jobs:
  build:
    docker:
      - image: gcr.io/compact-factor-192404/crypto-signal:master
        auth:
          username: _json_key
          password: $GOOGLE_AUTH
      - steps:
        - run:
            name: Dump GCP creds
            command: echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json
    steps:
      - checkout
      - run:
          name: Auth with GCP
          command: gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
      - run:
          name: Set GCP Project Id
          command: gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
      - run:
          name: Set GCP Compute Zone
          command: gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - run:
          name: Build
          command: make build
      - run:
          name: Publish
          command: make publish
